import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useTranslation from 'next-translate/useTranslation'
import i18nConfig from '../i18n.json'
import Link from 'next/link'

const { locales } = i18nConfig

const Home: NextPage = () => {
  const { t, lang } = useTranslation("common")
  const title = t("title")
  const home = t("home:home")

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span>{home}</span>
        {
          locales.map((lng) => {
            if (lng === lang) return null

            return (
              <Link href="/" locale={lng} key={lng}>
                <a style={{backgroundColor: "lightgray", padding: "10px", borderRadius: "10px"}}>Switch to {lng}</a>
              </Link>
            )
          })
        }
      </main>

    </div>
  )
}

export default Home
